// <auto-generated />
using System;
using AlkemyWallet.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlkemyWallet.Migrations
{
    [DbContext(typeof(WalletDbContext))]
    [Migration("20221112131158_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlkemyWallet.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<float>("Money")
                        .HasColumnType("real");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("User_id");

                    b.ToTable("Account", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(1995, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 150000f,
                            Userid = 2
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2021, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = true,
                            IsDeleted = false,
                            Money = 50f,
                            Userid = 2
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(1995, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 1050f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(1995, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 51234f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2018, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = true,
                            IsDeleted = false,
                            Money = 1224f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2001, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 25040f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(1995, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 55553f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2012, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = true,
                            IsDeleted = false,
                            Money = 50f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(1942, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 120f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(1995, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 54311f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2018, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = true,
                            IsDeleted = false,
                            Money = 3333f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2013, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 231f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(1995, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 1050f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(1995, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 51234f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTime(2018, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = true,
                            IsDeleted = false,
                            Money = 1224f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTime(2001, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 25040f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTime(1995, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 55553f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTime(2012, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = true,
                            IsDeleted = false,
                            Money = 50f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTime(1942, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 120f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateTime(1995, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 54311f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 21,
                            CreationDate = new DateTime(2018, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = true,
                            IsDeleted = false,
                            Money = 3333f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 22,
                            CreationDate = new DateTime(2013, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 231f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 23,
                            CreationDate = new DateTime(1998, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 1050f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 24,
                            CreationDate = new DateTime(1999, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 51234f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 25,
                            CreationDate = new DateTime(2018, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = true,
                            IsDeleted = false,
                            Money = 1224f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 26,
                            CreationDate = new DateTime(2011, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 25040f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 27,
                            CreationDate = new DateTime(1985, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 55553f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 28,
                            CreationDate = new DateTime(2022, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = true,
                            IsDeleted = false,
                            Money = 50f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 29,
                            CreationDate = new DateTime(1967, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 120f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 30,
                            CreationDate = new DateTime(1978, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 54311f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 31,
                            CreationDate = new DateTime(2020, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = true,
                            IsDeleted = false,
                            Money = 3333f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 32,
                            CreationDate = new DateTime(2019, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 231f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 33,
                            CreationDate = new DateTime(1992, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 1050f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 34,
                            CreationDate = new DateTime(1991, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 51234f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 35,
                            CreationDate = new DateTime(2017, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = true,
                            IsDeleted = false,
                            Money = 1224f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 36,
                            CreationDate = new DateTime(2007, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 25040f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 37,
                            CreationDate = new DateTime(1985, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 55553f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 38,
                            CreationDate = new DateTime(2008, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = true,
                            IsDeleted = false,
                            Money = 50f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 39,
                            CreationDate = new DateTime(1981, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 120f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 40,
                            CreationDate = new DateTime(1998, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 54311f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 41,
                            CreationDate = new DateTime(2018, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = true,
                            IsDeleted = false,
                            Money = 3333f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 42,
                            CreationDate = new DateTime(2013, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 231f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 43,
                            CreationDate = new DateTime(1995, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 1050f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 44,
                            CreationDate = new DateTime(1995, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 51234f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 45,
                            CreationDate = new DateTime(2018, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = true,
                            IsDeleted = false,
                            Money = 1224f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 46,
                            CreationDate = new DateTime(2001, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 25040f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 47,
                            CreationDate = new DateTime(1996, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 55553f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 48,
                            CreationDate = new DateTime(2015, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = true,
                            IsDeleted = false,
                            Money = 50f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 49,
                            CreationDate = new DateTime(1976, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 120f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 50,
                            CreationDate = new DateTime(1998, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 54311f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 51,
                            CreationDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = true,
                            IsDeleted = false,
                            Money = 3333f,
                            Userid = 1
                        },
                        new
                        {
                            Id = 52,
                            CreationDate = new DateTime(2012, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsBlocked = false,
                            IsDeleted = false,
                            Money = 231f,
                            Userid = 1
                        });
                });

            modelBuilder.Entity("AlkemyWallet.Entities.Catalogue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Product_description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Catalogue", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "",
                            IsDeleted = false,
                            Points = 300,
                            Productdescription = "cocina"
                        },
                        new
                        {
                            Id = 2,
                            Image = "",
                            IsDeleted = false,
                            Points = 500,
                            Productdescription = "Lavarropas"
                        },
                        new
                        {
                            Id = 3,
                            Image = "",
                            IsDeleted = false,
                            Points = 700,
                            Productdescription = "Heladera"
                        },
                        new
                        {
                            Id = 4,
                            Image = "",
                            IsDeleted = false,
                            Points = 400,
                            Productdescription = "Lavavajillas"
                        },
                        new
                        {
                            Id = 5,
                            Image = "",
                            IsDeleted = false,
                            Points = 600,
                            Productdescription = "Freezer"
                        },
                        new
                        {
                            Id = 6,
                            Image = "",
                            IsDeleted = false,
                            Points = 200,
                            Productdescription = "Microondas"
                        },
                        new
                        {
                            Id = 7,
                            Image = "",
                            IsDeleted = false,
                            Points = 400,
                            Productdescription = "Horno Electrico"
                        },
                        new
                        {
                            Id = 8,
                            Image = "",
                            IsDeleted = false,
                            Points = 500,
                            Productdescription = "Horno Grande"
                        },
                        new
                        {
                            Id = 9,
                            Image = "",
                            IsDeleted = false,
                            Points = 200,
                            Productdescription = "Panificadora"
                        },
                        new
                        {
                            Id = 10,
                            Image = "",
                            IsDeleted = false,
                            Points = 100,
                            Productdescription = "Cepillo Electrico"
                        },
                        new
                        {
                            Id = 11,
                            Image = "",
                            IsDeleted = false,
                            Points = 600,
                            Productdescription = "Termotanque"
                        },
                        new
                        {
                            Id = 12,
                            Image = "",
                            IsDeleted = false,
                            Points = 300,
                            Productdescription = "Secaropa"
                        },
                        new
                        {
                            Id = 13,
                            Image = "",
                            IsDeleted = false,
                            Points = 100,
                            Productdescription = "Tostadora"
                        },
                        new
                        {
                            Id = 14,
                            Image = "",
                            IsDeleted = false,
                            Points = 100,
                            Productdescription = "Plancha de pelo"
                        },
                        new
                        {
                            Id = 15,
                            Image = "",
                            IsDeleted = false,
                            Points = 300,
                            Productdescription = "Home Theater"
                        },
                        new
                        {
                            Id = 16,
                            Image = "",
                            IsDeleted = false,
                            Points = 250,
                            Productdescription = "Equipo de Sonido"
                        },
                        new
                        {
                            Id = 17,
                            Image = "",
                            IsDeleted = false,
                            Points = 400,
                            Productdescription = "Calentador Portatil"
                        },
                        new
                        {
                            Id = 18,
                            Image = "",
                            IsDeleted = false,
                            Points = 800,
                            Productdescription = "Televisor Led"
                        },
                        new
                        {
                            Id = 19,
                            Image = "",
                            IsDeleted = false,
                            Points = 50,
                            Productdescription = "Lampara de Pie"
                        },
                        new
                        {
                            Id = 20,
                            Image = "",
                            IsDeleted = false,
                            Points = 300,
                            Productdescription = "Sistema de Audio Portatil"
                        },
                        new
                        {
                            Id = 21,
                            Image = "",
                            IsDeleted = false,
                            Points = 100,
                            Productdescription = "Licuadora"
                        },
                        new
                        {
                            Id = 22,
                            Image = "",
                            IsDeleted = false,
                            Points = 350,
                            Productdescription = "Corta Cesped"
                        },
                        new
                        {
                            Id = 23,
                            Image = "",
                            IsDeleted = false,
                            Points = 200,
                            Productdescription = "Hidrolavadora"
                        },
                        new
                        {
                            Id = 24,
                            Image = "",
                            IsDeleted = false,
                            Points = 400,
                            Productdescription = "Telefono Celular"
                        },
                        new
                        {
                            Id = 25,
                            Image = "",
                            IsDeleted = false,
                            Points = 400,
                            Productdescription = "Generador Electrico"
                        },
                        new
                        {
                            Id = 26,
                            Image = "",
                            IsDeleted = false,
                            Points = 150,
                            Productdescription = "Bomba de Presion"
                        },
                        new
                        {
                            Id = 27,
                            Image = "",
                            IsDeleted = false,
                            Points = 800,
                            Productdescription = "Computadora de Escritorio"
                        },
                        new
                        {
                            Id = 28,
                            Image = "",
                            IsDeleted = false,
                            Points = 700,
                            Productdescription = "Laptop"
                        },
                        new
                        {
                            Id = 29,
                            Image = "",
                            IsDeleted = false,
                            Points = 250,
                            Productdescription = "Monitor UltraWide"
                        },
                        new
                        {
                            Id = 30,
                            Image = "",
                            IsDeleted = false,
                            Points = 500,
                            Productdescription = "Aire Acondicionado"
                        });
                });

            modelBuilder.Entity("AlkemyWallet.Entities.FixedTermDeposit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Account_id")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Closing_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Creation_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Account_id");

                    b.HasIndex("User_id");

                    b.ToTable("FixedTermDeposit", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accountid = 3,
                            Amount = 23000m,
                            Closingdate = new DateTime(2021, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2020, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 1
                        },
                        new
                        {
                            Id = 2,
                            Accountid = 3,
                            Amount = 23000m,
                            Closingdate = new DateTime(2022, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2021, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 1
                        },
                        new
                        {
                            Id = 3,
                            Accountid = 2,
                            Amount = 23000m,
                            Closingdate = new DateTime(2011, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2010, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 2
                        },
                        new
                        {
                            Id = 4,
                            Accountid = 2,
                            Amount = 23000m,
                            Closingdate = new DateTime(2019, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2018, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 2
                        },
                        new
                        {
                            Id = 5,
                            Accountid = 3,
                            Amount = 23000m,
                            Closingdate = new DateTime(2021, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2020, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 1
                        },
                        new
                        {
                            Id = 6,
                            Accountid = 3,
                            Amount = 23000m,
                            Closingdate = new DateTime(2022, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2021, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 1
                        },
                        new
                        {
                            Id = 7,
                            Accountid = 2,
                            Amount = 23000m,
                            Closingdate = new DateTime(2011, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2010, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 2
                        },
                        new
                        {
                            Id = 8,
                            Accountid = 2,
                            Amount = 23000m,
                            Closingdate = new DateTime(2019, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2018, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 2
                        },
                        new
                        {
                            Id = 9,
                            Accountid = 3,
                            Amount = 23000m,
                            Closingdate = new DateTime(2021, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2020, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 1
                        },
                        new
                        {
                            Id = 10,
                            Accountid = 3,
                            Amount = 23000m,
                            Closingdate = new DateTime(2022, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2021, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 1
                        },
                        new
                        {
                            Id = 11,
                            Accountid = 3,
                            Amount = 23000m,
                            Closingdate = new DateTime(2021, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2020, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 1
                        },
                        new
                        {
                            Id = 12,
                            Accountid = 3,
                            Amount = 23000m,
                            Closingdate = new DateTime(2022, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2021, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 1
                        },
                        new
                        {
                            Id = 13,
                            Accountid = 2,
                            Amount = 23000m,
                            Closingdate = new DateTime(2011, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2010, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 2
                        },
                        new
                        {
                            Id = 14,
                            Accountid = 2,
                            Amount = 23000m,
                            Closingdate = new DateTime(2019, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2018, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 2
                        },
                        new
                        {
                            Id = 15,
                            Accountid = 3,
                            Amount = 23000m,
                            Closingdate = new DateTime(2021, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2020, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 1
                        },
                        new
                        {
                            Id = 16,
                            Accountid = 3,
                            Amount = 23000m,
                            Closingdate = new DateTime(2022, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2021, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 1
                        },
                        new
                        {
                            Id = 17,
                            Accountid = 2,
                            Amount = 23000m,
                            Closingdate = new DateTime(2011, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2010, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 2
                        },
                        new
                        {
                            Id = 18,
                            Accountid = 2,
                            Amount = 23000m,
                            Closingdate = new DateTime(2019, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2018, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 2
                        },
                        new
                        {
                            Id = 19,
                            Accountid = 3,
                            Amount = 23000m,
                            Closingdate = new DateTime(2021, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2020, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 1
                        },
                        new
                        {
                            Id = 20,
                            Accountid = 3,
                            Amount = 23000m,
                            Closingdate = new DateTime(2022, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2021, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 1
                        },
                        new
                        {
                            Id = 21,
                            Accountid = 3,
                            Amount = 23000m,
                            Closingdate = new DateTime(2021, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2020, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 1
                        },
                        new
                        {
                            Id = 22,
                            Accountid = 3,
                            Amount = 23000m,
                            Closingdate = new DateTime(2022, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2021, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 1
                        },
                        new
                        {
                            Id = 23,
                            Accountid = 2,
                            Amount = 23000m,
                            Closingdate = new DateTime(2011, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2010, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 2
                        },
                        new
                        {
                            Id = 24,
                            Accountid = 2,
                            Amount = 23000m,
                            Closingdate = new DateTime(2019, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2018, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 2
                        },
                        new
                        {
                            Id = 25,
                            Accountid = 3,
                            Amount = 23000m,
                            Closingdate = new DateTime(2021, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2020, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 1
                        },
                        new
                        {
                            Id = 26,
                            Accountid = 3,
                            Amount = 23000m,
                            Closingdate = new DateTime(2022, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2021, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 1
                        },
                        new
                        {
                            Id = 27,
                            Accountid = 2,
                            Amount = 23000m,
                            Closingdate = new DateTime(2011, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2010, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 2
                        },
                        new
                        {
                            Id = 28,
                            Accountid = 2,
                            Amount = 23000m,
                            Closingdate = new DateTime(2019, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2018, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 2
                        },
                        new
                        {
                            Id = 29,
                            Accountid = 3,
                            Amount = 23000m,
                            Closingdate = new DateTime(2021, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2020, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 1
                        },
                        new
                        {
                            Id = 30,
                            Accountid = 3,
                            Amount = 23000m,
                            Closingdate = new DateTime(2022, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2021, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 1
                        },
                        new
                        {
                            Id = 31,
                            Accountid = 3,
                            Amount = 23000m,
                            Closingdate = new DateTime(2021, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2020, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 1
                        },
                        new
                        {
                            Id = 32,
                            Accountid = 3,
                            Amount = 23000m,
                            Closingdate = new DateTime(2022, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2021, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 1
                        },
                        new
                        {
                            Id = 33,
                            Accountid = 2,
                            Amount = 23000m,
                            Closingdate = new DateTime(2011, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2010, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 2
                        },
                        new
                        {
                            Id = 34,
                            Accountid = 2,
                            Amount = 23000m,
                            Closingdate = new DateTime(2019, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2018, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 2
                        },
                        new
                        {
                            Id = 35,
                            Accountid = 3,
                            Amount = 23000m,
                            Closingdate = new DateTime(2021, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2020, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 1
                        },
                        new
                        {
                            Id = 36,
                            Accountid = 3,
                            Amount = 23000m,
                            Closingdate = new DateTime(2022, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2021, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 1
                        },
                        new
                        {
                            Id = 37,
                            Accountid = 2,
                            Amount = 23000m,
                            Closingdate = new DateTime(2011, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2010, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 2
                        },
                        new
                        {
                            Id = 38,
                            Accountid = 2,
                            Amount = 23000m,
                            Closingdate = new DateTime(2019, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2018, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 2
                        },
                        new
                        {
                            Id = 39,
                            Accountid = 3,
                            Amount = 23000m,
                            Closingdate = new DateTime(2021, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2020, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 1
                        },
                        new
                        {
                            Id = 40,
                            Accountid = 3,
                            Amount = 23000m,
                            Closingdate = new DateTime(2022, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creationdate = new DateTime(2021, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Userid = 1
                        });
                });

            modelBuilder.Entity("AlkemyWallet.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Admin",
                            IsDeleted = false,
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Usuario con algunos permisos de escritura",
                            IsDeleted = false,
                            Name = "Standard"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Solo permisos de lectura",
                            IsDeleted = false,
                            Name = "Invitado"
                        });
                });

            modelBuilder.Entity("AlkemyWallet.Entities.Transaction", b =>
                {
                    b.Property<int>("Transaction_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Transaction_id"));

                    b.Property<int>("Account_id")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("Concept")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Concept");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int>("To_Account")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Type");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Transaction_id");

                    b.HasIndex("Account_id");

                    b.HasIndex("User_id");

                    b.ToTable("Transaction", (string)null);

                    b.HasData(
                        new
                        {
                            Transactionid = 1,
                            Accountid = 1,
                            Amount = 15155,
                            Concept = "Crédito",
                            Date = new DateTime(2020, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Efectivo",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 2,
                            Accountid = 1,
                            Amount = 4922,
                            Concept = "Efectivo",
                            Date = new DateTime(1999, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Debito",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 3,
                            Accountid = 1,
                            Amount = 9340,
                            Concept = "Prestamo",
                            Date = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Crédito",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 4,
                            Accountid = 1,
                            Amount = 3211,
                            Concept = "Sueldo",
                            Date = new DateTime(2013, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Efectivo",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 5,
                            Accountid = 1,
                            Amount = 55552,
                            Concept = "crédito",
                            Date = new DateTime(2022, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Efectivo",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 6,
                            Accountid = 1,
                            Amount = 224,
                            Concept = "Reintegro",
                            Date = new DateTime(1980, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Debito",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 7,
                            Accountid = 1,
                            Amount = 202300,
                            Concept = "Pago",
                            Date = new DateTime(1994, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Efectivo",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 8,
                            Accountid = 1,
                            Amount = 202300,
                            Concept = "Pago",
                            Date = new DateTime(1990, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Efectivo",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 9,
                            Accountid = 1,
                            Amount = 202300,
                            Concept = "Pago",
                            Date = new DateTime(1990, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Credito",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 10,
                            Accountid = 1,
                            Amount = 202300,
                            Concept = "Sueldo",
                            Date = new DateTime(1990, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Efectivo",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 11,
                            Accountid = 1,
                            Amount = 15155,
                            Concept = "Crédito",
                            Date = new DateTime(2020, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Efectivo",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 12,
                            Accountid = 1,
                            Amount = 4922,
                            Concept = "Efectivo",
                            Date = new DateTime(1999, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Debito",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 13,
                            Accountid = 1,
                            Amount = 9340,
                            Concept = "Prestamo",
                            Date = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Crédito",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 14,
                            Accountid = 1,
                            Amount = 3211,
                            Concept = "Sueldo",
                            Date = new DateTime(2013, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Efectivo",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 15,
                            Accountid = 1,
                            Amount = 55552,
                            Concept = "crédito",
                            Date = new DateTime(2022, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Efectivo",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 16,
                            Accountid = 1,
                            Amount = 224,
                            Concept = "Reintegro",
                            Date = new DateTime(1980, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Debito",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 17,
                            Accountid = 1,
                            Amount = 202300,
                            Concept = "Pago",
                            Date = new DateTime(1990, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Efectivo",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 18,
                            Accountid = 1,
                            Amount = 202300,
                            Concept = "Pago",
                            Date = new DateTime(1990, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Efectivo",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 19,
                            Accountid = 1,
                            Amount = 202300,
                            Concept = "Pago",
                            Date = new DateTime(1993, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Credito",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 20,
                            Accountid = 1,
                            Amount = 202300,
                            Concept = "Sueldo",
                            Date = new DateTime(1995, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Efectivo",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 21,
                            Accountid = 1,
                            Amount = 15155,
                            Concept = "Crédito",
                            Date = new DateTime(2020, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Efectivo",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 22,
                            Accountid = 1,
                            Amount = 4922,
                            Concept = "Efectivo",
                            Date = new DateTime(1999, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Debito",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 23,
                            Accountid = 1,
                            Amount = 9340,
                            Concept = "Prestamo",
                            Date = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Crédito",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 24,
                            Accountid = 1,
                            Amount = 3211,
                            Concept = "Sueldo",
                            Date = new DateTime(2013, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Efectivo",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 25,
                            Accountid = 1,
                            Amount = 55552,
                            Concept = "crédito",
                            Date = new DateTime(2022, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Efectivo",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 26,
                            Accountid = 1,
                            Amount = 224,
                            Concept = "Reintegro",
                            Date = new DateTime(1980, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Debito",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 27,
                            Accountid = 1,
                            Amount = 202300,
                            Concept = "Pago",
                            Date = new DateTime(1990, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Efectivo",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 28,
                            Accountid = 1,
                            Amount = 202300,
                            Concept = "Pago",
                            Date = new DateTime(1991, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Efectivo",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 29,
                            Accountid = 1,
                            Amount = 202300,
                            Concept = "Pago",
                            Date = new DateTime(1997, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Credito",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 30,
                            Accountid = 1,
                            Amount = 202300,
                            Concept = "Sueldo",
                            Date = new DateTime(1998, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Efectivo",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 31,
                            Accountid = 1,
                            Amount = 15155,
                            Concept = "Crédito",
                            Date = new DateTime(2019, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Efectivo",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 32,
                            Accountid = 1,
                            Amount = 4922,
                            Concept = "Efectivo",
                            Date = new DateTime(1999, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Debito",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 33,
                            Accountid = 1,
                            Amount = 9340,
                            Concept = "Prestamo",
                            Date = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Crédito",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 34,
                            Accountid = 1,
                            Amount = 3211,
                            Concept = "Sueldo",
                            Date = new DateTime(2013, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Efectivo",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 35,
                            Accountid = 1,
                            Amount = 55552,
                            Concept = "crédito",
                            Date = new DateTime(2021, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Efectivo",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 36,
                            Accountid = 1,
                            Amount = 224,
                            Concept = "Reintegro",
                            Date = new DateTime(1980, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Debito",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 37,
                            Accountid = 1,
                            Amount = 202300,
                            Concept = "Pago",
                            Date = new DateTime(1992, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Efectivo",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 38,
                            Accountid = 1,
                            Amount = 202300,
                            Concept = "Pago",
                            Date = new DateTime(1991, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Efectivo",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 39,
                            Accountid = 1,
                            Amount = 202300,
                            Concept = "Pago",
                            Date = new DateTime(1997, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Credito",
                            Userid = 1
                        },
                        new
                        {
                            Transactionid = 40,
                            Accountid = 1,
                            Amount = 202300,
                            Concept = "Sueldo",
                            Date = new DateTime(1999, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ToAccount = 0,
                            Type = "Efectivo",
                            Userid = 1
                        });
                });

            modelBuilder.Entity("AlkemyWallet.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int>("Points")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("Rol_id")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Rol_id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "clint@eastwood.com",
                            Firstname = "Clint",
                            IsDeleted = false,
                            Lastname = "Eastwood",
                            Password = "$2b$10$DjsYH6P2iczga6DFAAVf/Oulu1f9Qdlw24w0Lfej3aNnQx.eqato2",
                            Points = 500,
                            Rolid = 2
                        },
                        new
                        {
                            Id = 2,
                            Email = "arnoldsg@skynet.com",
                            Firstname = "Arnold",
                            IsDeleted = false,
                            Lastname = "Schwarzenegger",
                            Password = "$2b$10$dvsbNpgI0E0v9X5D7r9h2un6DFsI8mx2RePLUOUaMMTWQr3hlU522",
                            Points = 2000,
                            Rolid = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "sylvesters@hollywood.com",
                            Firstname = "Sylvester",
                            IsDeleted = false,
                            Lastname = "Stallone",
                            Password = "$2b$10$zUJTo0YB6ltWZFwFUw3Ek.47UuzqwFNI366GhKoTJZlUQkPS..mNu",
                            Points = 2000,
                            Rolid = 3
                        });
                });

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AlkemyWallet.Entities.Account", b =>
                {
                    b.HasOne("AlkemyWallet.Entities.User", "User")
                        .WithMany("Account")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlkemyWallet.Entities.FixedTermDeposit", b =>
                {
                    b.HasOne("AlkemyWallet.Entities.Account", "Account")
                        .WithMany("FixedTermDeposit")
                        .HasForeignKey("Account_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlkemyWallet.Entities.User", "User")
                        .WithMany("FixedTermDeposit")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlkemyWallet.Entities.Transaction", b =>
                {
                    b.HasOne("AlkemyWallet.Entities.Account", "Account")
                        .WithMany("Transaction")
                        .HasForeignKey("Account_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlkemyWallet.Entities.User", "User")
                        .WithMany("Transaction")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlkemyWallet.Entities.User", b =>
                {
                    b.HasOne("AlkemyWallet.Entities.Role", "Role")
                        .WithMany("User")
                        .HasForeignKey("Rol_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AlkemyWallet.Entities.Account", b =>
                {
                    b.Navigation("FixedTermDeposit");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("AlkemyWallet.Entities.Role", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("AlkemyWallet.Entities.User", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("FixedTermDeposit");

                    b.Navigation("Transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
